### ISSUE TITLE
Resource descriptions should describe what the resource is about

### ISSUE THREAD

**Issue by hsolbrig** [biocaddie/WG3-MetadataSpecifications#16]
The current resource descriptions start with: "JSON-schema representing ..." (e.g. activity_schema.json -- description: JSON-schema representing an activity/process in the DDI model....).  This looks odd when the schema is translated into other representations -- OWL, XML Schema, UML Models, etc.  We would recommend that the names be changed to identify what an instance of the schema _represents_, not a description of what we are looking at.  As an example, the activity description might read
""description": "An activity/process in the DDI model. A type of process scheduled in a study".  Similarly, the "title" attribute would make more sense described as:
"description": "The title/name of the process" instead of
"description": "_a property to specify_ the title/name of the process",

**Comment by agbeltran** [comment]
Totally agree! We will change the descriptions. Thanks

**Comment by agbeltran** [comment]
The descriptions have been changed for all the entities/properties.
