### ISSUE TITLE
ClinicalTrials.gov

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/WG3-MetadataSpecifications#17]
/* Not in the metadata model */

/* Data monitoring committee */
transform column "$.'clinical_study'.'oversight_info'.'authority'.'_$'" to "clinicalStudy.oversight_info.authority";  
transform column "$.'clinical_study'.'oversight_info'.'has_dmc'.'_$'" to "clinicalStudy.oversight_info.has_dmc";

transform column "$.'clinical_study'.'overall_status'.'_$'" to "study.status";
transform column "$.'clinical_study'.'phase'.'_$'" to "study.phase";
transform column "$.'clinical_study'.'arm_group'[*].'arm_group_type'.'_$'" to "studyGroup.type[]";
transform column "$.'clinical_study'.'arm_group'[*].'description'.'_$'" to "studyGroup.description[]";  
transform column "$.'clinical_study'.'verification_date'.'_$'" to "dataset.verificationDate";
transform column "$.'clinical_study'.'is_fda_regulated'.'_$'" to "dataset.is_fda_regulated"; 
transform column "$.'clinical_study'.'has_expanded_access'.'_$'" to "dataset.has_expanded_access";

/* In first iteration we can leave this - however, this should be added to the WG2 issue tracker as something to discuss with WG3 */
transform column "$.'clinical_study'.'arm_group'[*].'description'.'_$'" to "studyGroup.description[]";  
transform column "$.'clinical_study'.'intervention'.'intervention_type'.'_$'" to "treatment.title";
transform column "$.'clinical_study'.'intervention'.'intervention_name'.'_$'" to "treatment.agent";
transform column "$.'clinical_study'.'intervention'.'description'.'_$'" to "treatment.description";
transform column "$.'clinical_study'.'eligibility'.'criteria'.'textblock'.'_$'" to "study.recruits.criteria";
transform column "$.'clinical_study'.'eligibility'.'gender'.'_$'" to "study.recruits.gender";
transform column "$.'clinical_study'.'eligibility'.'minimum_age'.'_$'" to "study.recruits.minimum_age";
transform column "$.'clinical_study'.'eligibility'.'maximum_age'.'_$'" to "study.recruits.maximum_age";

/* In first iteration we can leave this - however, this should be added to the WG3 issue tracker as something to discuss with WG3 */
For other countries we need to turn that into a multi value array*/
transform column "$.'clinical_study'.'location'.'facility'.'name'.'_$'" to "study.location.name";
transform column "$.'clinical_study'.'location'.'facility'.'address'.'city'.'_$'" to "study.location.city";
transform column "$.'clinical_study'.'location'.'facility'.'address'.'zip'.'_$'" to "study.location.zip";
transform column "$.'clinical_study'.'location'.'facility'.'address'.'country'.'_$'" to "study.location.country";
transform column "$.'clinical_study'.'location_countries'.'country'.'_$'" to "study.location.othercountries[0]";

**Comment by agbeltran** [comment]
Hi @RuilingLiu, we are trying to interpret what you consider missing from your transformation file.
Is it correct that you are saying that the DATS model is missing elements to:
studyGroup.type
studyGroup.description
?
Are you saying we might need to move studyGroup.selectionCriteria to study.selectionCriteria?
And we might need to add a relationship from studyGroup to Treatment?

**Comment by RuilingLiu** [comment]
Hi @agbeltran ,

I am not sure about the metadata. I think @jgrethe may know the answers.

**Comment by agbeltran** [comment]
@jgrethe following up on this, we have produced this example of ClinicalTrials.gov with DATS:

https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/examples/ClinicalTrials.gov-NCT00001372.json

Maybe this help in identifying if everything is covered?

**Comment by agbeltran** [comment]
Closing this issue now, please let us know if the example we shared for clinicaltrials.gov is not enough.
