### ISSUE TITLE
granularity issue around Person designation

### ISSUE THREAD

**Issue by proccaserra** [biocaddie/WG3-MetadataSpecifications#2]
some ask for more information, such as 'Mid Initial'.
other would rather have all the information lumped in one attribute, owing to the difficulty to assigned the result of a string split to either 'first name' or 'last name'.

**Comment by proccaserra** [comment]
We followed patterns used by Pubmed to document individual author information.

http://www.ncbi.nlm.nih.gov/books/NBK3828/

**Comment by agbeltran** [comment]
Decision: we are adding 'mid initial' and 'full name' in the person entity to cover all options for ingesting datasets from different sources (that may or not have separate fields for each section of the name)
