### ISSUE TITLE
Association to License differs between Publication,Software,DataRepository,Standards and Distribution

### ISSUE THREAD

**Issue by proccaserra** [biocaddie/WG3-MetadataSpecifications#28]
Distribution can only be linked to licenses via an Access object and the accessModalities relations.

I am inclined to regularize the representation and move the 'license' element out of Access to bump it up to Distribution to be consistent with DataRepository, Publication,Software and Standards.

The alternative (which results in more involved navigation) means adding Access element to DataRepository, Publication,Software and Standards objects.

**Comment by agbeltran** [comment]
I think that the best solution would be indeed removing 'licenses' from 'Access' and adding 'licenses' to 'DatasetDistribution' directly. I will action this after discussion with Core Dev Team today.

**Comment by agbeltran** [comment]
It was agreed to action this change in DATS.

**Comment by agbeltran** [comment]
In addition, licenses should also be added at the Dataset level and not only at the DatasetDistribution level (given the information available in target repositories).
