### ISSUE TITLE
Ambiguity around 'homepage' attribute of Data Standards and Data Repository elements

### ISSUE THREAD

**Issue by proccaserra** [biocaddie/WG3-MetadataSpecifications#3]
Reported by Anu:

suggestion: 'within the index it may be better to keep this a generic type field (e.g. URL) as most items will have a URL and may not be called homepage'

**Comment by agbeltran** [comment]
Decision: to remove homepage from Data Standards and Data Repository entities; URLs will be addressed via an extended identification element.
