### ISSUE TITLE
why is license for dataset linked to DataDistribution?

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#34]
Seems like the license would be scoped to a dataset, not how it is distributed.

**Comment by agbeltran** [comment]
Licenses are considered in both Dataset and DatasetDistribution entities to reflect the fact that the information is present in one or other element in the different repositories.

This issue was discussed and addressed as part of issue #28.

**Comment by smrgeoinfo** [comment]
the concept map diagram is not synchronized with the JSON, various other resources have licenses as well.
