### ISSUE TITLE
Shouldn't Person-Dataset have created and createdBy predicates

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#35]
should have createdBy from dataset to person and inverse created from person to dataset.

**Comment by agbeltran** [comment]
The Dataset entity indeed contains a property 'creators' (one or more entities of types Person or Organization). See here: https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/dataset_schema.json

We don't represent the inverse property at the moment, as the focus is on Dataset and the index in DataMed can be built from this information.

**Comment by smrgeoinfo** [comment]
cmap diagrams out of sync with JSON schema.
