### ISSUE TITLE
relation from publication to dataset

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#36]
Shouldn't there be a relation like publication> 'basedOn' > dataset or publication > 'evidence' >dataset ?

Publication > cites > dataset is ambiguous  as to the actual relationship.

**Comment by agbeltran** [comment]
Currently, we represent relationship from Dataset and Publication (but the Publication entity does not include 'cites' Dataset, see here: https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/publication_schema.json).

In issue #31, we have addressed the different types of publications from a Dataset perspective, these being 'primaryPublications' (those describing how the dataset was produced) and 'citations' (those publications that reference the Dataset). The DATS model currently does not include the specific semantics of these citations, but it could be annotated with relevant ontologies if necessary.

You can see the current representation for Dataset (with properties and their definitions) here: 
https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/dataset_schema.json

Thanks for your feedback.

**Comment by smrgeoinfo** [comment]
cmap diagram out of sync with JSON.  Seems like 'sourceCitation' would be a better predicate than 'primaryPublication' but that's just my opinion.

**Comment by agbeltran** [comment]
Yes, the cmap has not been updated since the last release but it will be synchronised with the JSON schemas for the following release. I will communicate your suggestion w.r.t. 'sourceCitation' to the team, with whom we selected the 'primaryPublication' term. Thanks.
