### ISSUE TITLE
identifiers and alternateIdentifiers

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#37]
Since these are both arrays, there needs to be some clear guidance on what to represent as an Identifier and what to represent as an alternateIdentifier (I'm a newbie, and haven't studied all the docs...)

**Comment by agbeltran** [comment]
Thanks for the note. Indeed this needs more clarification and we are producing documentation to take that into account and revising the cardinality for these elements (possibly making identifier with cardinality 1). When considering identifiers and alternateIdentifiers, we looked into DataCite approach (see http://schema.datacite.org/) where the identifier is considered a unique string identifying the resource and alternateIdentifiers are other identifiers for the same resource, which can also be local.
