### ISSUE TITLE
relatedIdentifiers or relatedResources

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#38]
Since the intention of relatedIdentifers is to provide links to related resources (correct me if I'm wrong), wouldn't 'relatedResources' be a clearer key name?

**Comment by agbeltran** [comment]
The name 'relatedIdentifiers' was used to align with the DataCite approach (see http://schema.datacite.org/) and it is indeed for reporting the identifiers of related resources. Thanks.
