### ISSUE TITLE
Elements in array for dimension_schema.values not defined

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#39]
the "type" property for the "values" key on dimension is "array", but the type for the objects in the array is not defined. Is this valid JSON schema v4?

**Comment by agbeltran** [comment]
We have left Dimension.values array items unspecified not to restrict the dimension values, and it does validate using our validation code. The json-schema specification confirms this, as for "items" it reads "The default value is an empty schema which allows any value for items in the instance array."
(see https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.5). Thanks
