### ISSUE TITLE
dataset has a storedIn attribute but doesn’t include the model for the data resource

### ISSUE THREAD

**Issue by proccaserra** [biocaddie/WG3-MetadataSpecifications#4]
Reported by Anu:
"Within the index the information for the resource should be stored with each record"

**Comment by agbeltran** [comment]
We think this is addressed as the 'DatasetDistribution' has information on the DataRepository (one or more) where it is stored. @aegururaj let us know if this doesn't cover what you were reporting and please re-open the issue with more details in that case. Thanks.
