### ISSUE TITLE
values in category_values_pair--why not type as annotation

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#40]
the category_values_pair allows an array of value strings and an array of valueIRI, which does not make explicit binding between a string value (what I'd think of as a label) and an IRI for the value. Why not use annotation object which does allow binding between a string and an IRI:
 "values": {
      "description": "A set of values associated with the cateogory.",
      "type": "array",
      "items": {
        "$ref" : "annotation_schema.json#"
      }
    }

**Comment by agbeltran** [comment]
Thanks for the note - indeed, that would be a better way to do it.
