### ISSUE TITLE
Add dataset qualifiers

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/WG3-MetadataSpecifications#42]
As discussed with CDT, we are adding the following qualifiers for Dataset:

- availability: A qualifier indicating the different types of availability for a dataset (available, unavailable, embargoed, available with restriction, information not available). Type: string
- refinement: A qualifier indicating if the entity represents an 'instance of dataset' or a 'collection of datasets'.	 Type: string
- aggregation: A qualifier indicating if the entity represents an 'instance of dataset' or a 'collection of datasets'.	Type: string

The CVs for these qualifiers are being defined.

**Comment by yul129** [comment]
Refinement and aggregation have the same representations?

**Comment by agbeltran** [comment]
No, that was a mistake. Thanks for spotting it! Fixing now...

**Comment by agbeltran** [comment]
refinement: A qualifier to describe the level of data processing of the dataset and its distributions.
