### ISSUE TITLE
explanation of material as a characteristic of a material

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#45]
the logic of why material.characteristic can have a value whose data type is a dimension  or a material is not clear. Dimension makes sense, its what I'd think of as a property of the material, but I don't get a material as a characteristic of a material. Is this confusing attribute-of with part-of relationships?

**Comment by agbeltran** [comment]
I think you are right and the range 'Material' should be removed.

**Comment by proccaserra** [comment]
one reasons for allowing Material to a be a filler for 'characteristics' is the following: to indicate it contains another material. Material = liver, with Characteristics[cell] whose value would be 'hepatocyte'.

**Comment by agbeltran** [comment]
Further to discussions with @proccaserra, and considering use cases such as that above, we will keep characteristics to have range both Dimension and Material. We will clarify in the documentation that in some cases, the property could be used to indicate part-of relationships. 
This actually follows an approach as some existing formats such as ISA-Tab and MAGE-Tab. 
So, I will close the issue now, but @smrgeoinfo please let us know if more clarifications are required.

**Comment by smrgeoinfo** [comment]
I guess the interpretation that is indended is 'if the characteristic has a value of type 'material' then the semantics are 'has part', if the characteristic has a value of type 'dimension', the semantics are given by the 'types' key on the dimension.   Seems like unnecessary overloading of the characteristics key, and offers the possibility of representing parts either as characteristic/material or characteristic/dimension[type='has part'].  It'll work as long as everyone follows carefully documented conventions.

**Comment by agbeltran** [comment]
Yes, we agree. Following the curation guidelines will be key.
