### ISSUE TITLE
dataset.isAbout-- shouldn't this be a link

### ISSUE THREAD

**Issue by smrgeoinfo** [biocaddie/WG3-MetadataSpecifications#46]
In trying to imagine what an implementation of DataSet.isAbout would look like, I can only guess that it would be an array of Identifiers (a URI) or Annotations (a label (aka value) or a URI).  Perhaps it would make more sense to make the data type something like Annotation

**Comment by agbeltran** [comment]
The reason for including the different types for Dataset.isAbout is to support specific semantics (e.g. begin able to say that the Dataset is about a specific Disease). But I see your point that we could also add a generic annotation, so I will extend the range to include Annotation too.

**Comment by agbeltran** [comment]
Closing via commit 89664f72a9ad9b14c2b255205f0fdb9c5f2265e4

**Comment by smrgeoinfo** [comment]
That's an improvement, but I think you'd be better off with a value type more like category_values_pair-- lets you assert disease as the category and a specific disease as a value.  Hard typing puts a limitation on possibilities when the intention is to leave it pretty open ended.

**Comment by agbeltran** [comment]
Thanks for your comment - every entity has an 'extraProperties' attribute (also Dataset) whose value is CategoryValuePair allowing exactly what you described. According to our use cases, there are particular associations that people what to be able to identify such as those on isAbout (including Disease, TaxonomicInformation, etc). extraPorperties can be used for anything else. We will detail this in the documentaiton.
