### ISSUE TITLE
The DATS-sdo-context.jsonld File

### ISSUE THREAD

**Issue by johnmcampbell13** [biocaddie/WG3-MetadataSpecifications#47]
I was just looking around the specifications trying to figure out how to map ImmPort studies to bioCADDIE and I noticed what may be misspellings in the DATS-sdo-context.jsonld file. Not sure if it matters but it looks like in a couple of places (Study and Disease) "Medica" should be "Medical"

Thank you,
John Campbell

Study: {
@id: "lifescisdo:MedicaStudy",
@type: "@id"
},
StudyGroup: {
@id: "lifescisdo:MISSING",
@type: "@id"
},
Treatment: {
@id: "lifescisdo:MedicalProcedure",
@type: "@id"
},
Disease: {
@id: "lifescisdo:MedicaCondition",
@type: "@id"
},

**Comment by agbeltran** [comment]
Thanks John for revising this. That file is an old file (I will remove it now). Please, have a look at the context files for each entity.
