### ISSUE TITLE
Add geographical location where the dataset was created

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/WG3-MetadataSpecifications#48]
As discussed in CDT call 22 Nov 2016.

**Comment by jgrethe** [comment]
Is this if the dataset has a location - e.g. A sample taken at a specific location?

**Comment by agbeltran** [comment]
yes, this type of location is what we want to represent

**Comment by agbeltran** [comment]
Additional comments for this issue:
- by Xiaoqian: " we hope the geolocation is associated with the source of the data. For example, dbGaP geo-location is about the demographics of their samples."
- by Ruiling, pointing examples referring to study location:
"The geography of the study “Genetic Association Studies in the Solomon Islanders” is SB (Solomon Islanders).

 

https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000493.v1.p1

https://datamed.org/display-item.php?repository=0001&id=AU2_b0XHeC0xdfX7MJ2Z&query=Genetic%20Association%20Studies%20in%20the%20Solomon%20Islanders

 

 

 

The geography of the study “The Sea Islands Genetic Network (SIGNET): Identifying genetic contributors to diabetes and dyslipidemia in African Americans” is US

 

https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000433.v1.p1

https://datamed.org/display-item.php?repository=0001&id=AU2_byJseC0xdfX7MJxY&query=The%20Sea%20Islands%20Genetic%20Network%20(SIGNET):%20Identifying%20genetic%20contributors%20to%20diabetes%20and%20dyslipidemia%20in%20African%20Americans
"

**Comment by smrgeoinfo** [comment]
doing spatial coverage as annotation provides very little interoperability. Wouldn't it be better to use e.g. DataCite geolocations?

**Comment by agbeltran** [comment]
Thank you very much for your comment. After analysing DataCite, but also GeoJSON and schema.org, we are adding the entity Place to cover this. See #50  and let us know if you have any comments. Thanks again.
