### ISSUE TITLE
need to determine a path detailing what to do with the extra data 

### ISSUE THREAD

**Issue by proccaserra** [biocaddie/WG3-MetadataSpecifications#5]
reported by Anu:
(i.e. the data that does not fit within the base model)

**Comment by agbeltran** [comment]
An extension mechanism has been defined, relying on a new entity for one or more `ExtraProperty`'s.

https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/extra_property_schema.json
