### ISSUE TITLE
OMOP mapping error

### ISSUE THREAD

**Issue by vojtechhuser** [biocaddie/WG3-MetadataSpecifications#55]
treatment can also be a procedure.

hence only mapping to drug_exposure provider is not complete

![image](https://user-images.githubusercontent.com/7526119/35066823-f026db88-fb9f-11e7-9ce1-17e0478f36b8.png)

in 
file 
https://raw.githubusercontent.com/biocaddie/WG3-MetadataSpecifications/7b74cca2a37c8979f78633424d2e2610e248f63d/json-instances/omop-cdm/DATS-OMOP.csv

**Comment by agbeltran** [comment]
@vojtechhuser thanks for raising this issue;  in the mapping file, we have (in line 307 of the csv file):

DATS.Treatment.performedBy associated with OMOP classes [DRUG_EXPOSURE](https://github.com/OHDSI/CommonDataModel/wiki/DRUG_EXPOSURE),  [DEVICE_EXPOSURE](https://github.com/OHDSI/CommonDataModel/wiki/DEVICE_EXPOSURE) and [PROCEDURE_OCURRENCE](https://github.com/OHDSI/CommonDataModel/wiki/PROCEDURE_OCCURRENCE), and OMOP property provider_id (that is available in the three classes).

So, I believe we are covering that Treatment can be a Procedure - or what were you suggesting we need to add?

Thanks

**Comment by vojtechhuser** [comment]
I see.

**Comment by agbeltran** [comment]
Thanks, @vojtechhuser - do you think there is anything to be corrected in the mapping?

**Comment by agbeltran** [comment]
Closing for now - please, feel free to re-open the issue if there is anything to fix.
