### ISSUE TITLE
dimension_schema.json doesn't specify data type for "values" property

### ISSUE THREAD

**Issue by MatthewRichardsonICPSR** [biocaddie/WG3-MetadataSpecifications#57]
It's not clear if values is supposed to be a string, number, annotation, or whatever.

**Comment by agbeltran** [comment]
Hi @MatthewRichardsonICPSR 
The reason the 'values' property of a 'Dimension' is left unspecified is to allow any structure for the values of a dimension. 
For example, see the representation of this [ICPSR variable](https://www.icpsr.umich.edu/icpsrweb/ICPSR/ssvd/studies/33581/datasets/0001/variables/AQ5):

https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-instances/ICPSR-Dimensions/Dimension-33581-0001-AQ5.json

Thanks

**Comment by MatthewRichardsonICPSR** [comment]
Ah, so "values" is an array of objects, not an array of strings. That makes this a lot clearer to me. Thanks.
