### ISSUE TITLE
Relax requirements on Data_Analysis sets 

### ISSUE THREAD

**Issue by proccaserra** [biocaddie/WG3-MetadataSpecifications#68]
to avoid a possible “infinite loop” of requirements when using Data_Analysis for a Dataset.
also: at Line 108: "required": [ "name", **"input", "output"** ]

and possibly: _Remove "minItems": 1_

 "input" : { 
"description": "The entities used as input.",
 "type": "array",
"items":{
"$ref" : "dataset_schema.json#"
}**,
 "minItems": 1**
 },
"output" : {
"description": "The entities resulting from applying the activity.",
"type": "array",
"items":{
"$ref" : "dataset_schema.json#"
}**,
"minItems": 1**
 },

**Comment by agbeltran** [comment]
Inadvertently, I duplicated this issue in  #74 - now implemented, closing.
