### ISSUE TITLE
data_analysis_schema.json

### ISSUE THREAD

**Issue by hsolbrig** [biocaddie/WG3-MetadataSpecifications#7]
According to the JSON-Schema specification, "allOf" references a list of objects, "each of which is a schema".  The "uses", "input" and "output" elements are objects.  We believe that the schema should read:

 "allOf": [
        {
            "$ref": "activity_schema.json#"
        },
        {
--->      "type": "object",
--->       "properties": {
                 "uses": { 
                    ...
                  "minItems" : 1
                  }
--->      }

This would be consistent with other uses of "allOf"

**Comment by agbeltran** [comment]
@hsolbrig thanks you very much for all the reports, we will fix the issues soon. 
We are also working on a new version of the model and we will make sure to update the JSON schemas to the new version (and we will make sure they are correct!)

**Comment by hsolbrig** [comment]
We (Dr. Jiang and Harold Solbrig, Mayo clinic) are using the schemas to create maps from dbGaP to bioCaddie submissions as well as to guide conversions to RDF for annotation.  We’ll be contacting you with a number of questions..
